# Настройки плагина AntiPodSos
settings:
  # Длительность защиты в секундах
  protection-time: 30

  # Цвет свечения предметов (RGB)
  glow-color:
    red: 255
    green: 0
    blue: 0

  # Разрешить PvP защиту
  enable-pvp-protection: true

  # Сообщения
  messages:
    loot-protected: "&cЭтот лут защищен! Подождите &e%time%&c секунд"
    loot-now-available: "&aТеперь можно забрать лут"
    killer-notification: "&aТолько вы можете забрать этот лут в течение &e%time%&a секунд"
    no-permission: "&cУ вас нет прав для этого!"
    config-reloaded: "&aКонфигурация перезагружена!"

  # Эффекты
  effects:
    enable-glow: true
    enable-particles: true
    particle-type: "FLAME"
    particle-count: 3